<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Gtamp.Adapters.Lspdfr</RootNamespace>
    <AssemblyName>Gtamp.Adapters.Lspdfr</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Gtamp.Shared\Gtamp.Shared.csproj" />
    <ProjectReference Include="..\Gtamp.Client.Core\Gtamp.Client.Core.csproj" />
  </ItemGroup>
</Project>
